### ISSUE TITLE
是否可以添加aarch64构建

### ISSUE THREAD

**Issue by 123485k** [ZianTT/BHYG#146]
如题，验证码模块经验证可以在aarch64架构上运行

**Comment by ZianTT** [comment]
action不支持aarch64，除非赞助给我一台aarch64的self hosted runner

**Comment by 123485k** [comment]
似乎可以尝试：[docker/setup-qemu-action](https://github.com/docker/setup-qemu-action)
或者其他类似的方案，使用qemu-user在amd64平台上直接运行aarch64工具链进行打包

**Comment by ZianTT** [comment]
以后再说，现阶段没有计划
