### ISSUE TITLE
抢河野华签售时有以下报错

### ISSUE THREAD

**Issue by dangdangpi** [ZianTT/BHYG#148]
程序出现错误，错误信息：'tuple' object has no attribute 'split' 错误追踪ID：8a760103be2f4a8f9301d718ce2491c9

河野华签售会编号：92528

**Comment by dangdangpi** [comment]
00:08:19.232 | ERROR    | 程序出现错误，错误信息：'tuple' object has no attribute 'split' 错误追踪ID：4361d90c965f45388abd726f8de32f17
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit

**Comment by dangdangpi** [comment]
[Uploading 20240920-000752.log…]()

**Comment by ZianTT** [comment]
> [Uploading 20240920-000752.log…]()
> 

传了又好像没传

**Comment by dangdangpi** [comment]
18:07:00.563 | WARNING  | ⚠️ 2745292335 不是脚本作者，望周知。（怎么会有小丑改个名就说是自己的了，笑死我了）
18:07:00.564 | INFO     | 提示: 
1. 提前在实用工具预填账号绑定手机号，可以不用开票时手忙脚乱填写！
2. 抢一张票，多开是没有用的！
3. 提前测试GT模块是否可用，方式：验证码登录/用户名密码登录，GT模块不能用建议换台电脑/系统！
18:08:09.359 | INFO     | 只沿用登录信息
18:08:09.363 | INFO     | 已使用自动时间偏移量，默认为NTP时间+0.5s
18:08:09.396 | INFO     | 已使用时间偏移：-0.70秒
18:08:09.600 | SUCCESS  | 用户 *** 登录成功
18:08:09.601 | INFO     | 用户为大会员，距离到期还有171.24天
18:08:10.580 | INFO     | 定时抢票已开启
18:08:11.495 | INFO     | 您当前使用的是本地GT模块验证码模式（推荐）
18:08:11.496 | INFO     | 常用项目ID如下：
18:08:11.497 | INFO     | 上海·BilibiliWorld 2024 id: 85939
18:08:11.497 | INFO     | 上海·BILIBILI MACRO LINK 2024 id: 85938
18:08:23.276 | INFO     | 项目名称：沈阳·第十三届SSCA动漫游戏博览会-河野华签售资格预约
18:08:23.993 | INFO     | 场次：10月1日
18:08:24.635 | INFO     | 票档：河野华签售预约票
18:08:24.637 | DEBUG    | 您的screen_id 和 sku_id 和 pay_money 分别为：204076 563389 100
18:08:24.637 | DEBUG    | 您的开始销售时间为：1727092800
18:08:24.714 | INFO     | 本项目只能购买一人票
18:08:24.724 | ERROR    | 程序出现错误，错误信息：list index out of range 错误追踪ID：6d96eb0de8c64159bf8c37a8dab1b2a1
18:08:26.746 | INFO     | 已安全退出，您可以关闭窗口（将在15秒后自动关闭）

**Comment by ZianTT** [comment]
fixed in commit eba13829f51b6e710ef590baff3e75a660d2e19f (priv repo)
