### ISSUE TITLE
[BUG]添加购票人失败

### ISSUE THREAD

**Issue by TaiMiao** [ZianTT/BHYG#149]
![2bf1360af8156e0edb7ebc3a94ef29f7](https://github.com/user-attachments/assets/6245370b-5453-427a-950e-fa39f861593e)
程序出现错误，错误信息：string indices must be integers, not 'str' 错误追踪ID：0c4c332b176c4fd29297680bb67cf6b1

**Comment by Violiate** [comment]
已修复，等待发版

**Comment by Violiate** [comment]
已修复，等待发版

**Comment by ZianTT** [comment]
> 已修复，等待发版

我勒个勤啊

有其他bug吗，感觉就为这一个发一个版怪怪的

**Comment by Violiate** [comment]
> > 已修复，等待发版
> 
> 我勒个勤啊
> 
> 有其他bug吗，感觉就为这一个发一个版怪怪的

好像也没什么…XD

**Comment by Violiate** [comment]
> > 已修复，等待发版
> 
> 我勒个勤啊
> 
> 有其他bug吗，感觉就为这一个发一个版怪怪的

好像也没什么其他bug…XD
