### ISSUE TITLE
[Bug]: 获取地址失败

### ISSUE THREAD

**Issue by jasonYellow** [ZianTT/BHYG#53]
### 描述这个Bug

通过https://show.bilibili.com/api/ticket/addr/list获取地址，addr_list是0，但实际已经添加了

### 复现步骤

正常运行程序，遇到需要寄纸质票的

### 预期操作

返回的addr_list不为0

### 问题版本

main分支-Release

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
好像看到了你的sentry跟踪了，我看看

**Comment by ZianTT** [comment]
发一下纸质票项目id，我看看是不是更新了

**Comment by jasonYellow** [comment]
82490

**Comment by ZianTT** [comment]
api应该还是可以使用的，地址确定有录入到系统内吗？会员购系统里面一般确认信息会有直接显示地址不需要填写才是录入成功

**Comment by jasonYellow** [comment]
![Uploading 20240319094119.jpg…]()
地址是有录入的

**Comment by jasonYellow** [comment]
![20240319094119](https://github.com/ZianTT/BHYG/assets/45000957/024fd833-a8f0-4afc-a38f-ccf788e31354)
地址是有录入的

**Comment by jasonYellow** [comment]
![20240319094119](https://github.com/ZianTT/BHYG/assets/45000957/0f1beb44-7a73-4c2f-a54f-52edc8703ee8)
地址是有录入的

**Comment by jasonYellow** [comment]
抱歉，是我这边的问题
