### ISSUE TITLE
[Bug]: 不晓得为什么卡在这个地方不动

### ISSUE THREAD

**Issue by schoolbag123** [ZianTT/BHYG#72]
### 描述这个Bug

我点重新配置，谷歌浏览器弹出监听窗口，但是没有后续反应

### 复现步骤

不清楚怎么在其他电脑上面复现

### 预期操作

应该是往下走才对

### 截图

<img width="817" alt="image" src="https://github.com/ZianTT/BHYG/assets/48409459/b4b2b7aa-3628-4ed5-ad4e-4dc03e29430a">
<img width="408" alt="image" src="https://github.com/ZianTT/BHYG/assets/48409459/dfcffa35-2e1f-494f-80ca-2e951066c96b">

### 问题版本

main分支-Release

### 我是最新版本

- [x] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by schoolbag123** [comment]
最新情况，卡了6分钟弹出QR码了，但是扫描确定以后程序继续没有反应

**Comment by ZianTT** [comment]
挂梯子了没？感觉要么电脑卡了要么网络状态不好

**Comment by schoolbag123** [comment]
的确应该是网络状态不好的问题，，，我换了一个网速度很快。佬能不能再给一个时间更长一点的key，不确定崩铁什么时候开票🥲

**Comment by ZianTT** [comment]
> 的确应该是网络状态不好的问题，，，我换了一个网速度很快，没有这个情况，麻了😅。佬能不能再给一个时间更长一点的key，不确定崩铁什么时候开票🥲

其实我建议抢捡漏票，这样出问题概率小（指被风控）建议找个网络环境好的地方挂着，因为我家网络环境好像也不咋地没抢到找朋友帮我抢十分钟拿下…

**Comment by schoolbag123** [comment]
唉唉，才挂了一下下就被412风控了

**Comment by ZianTT** [comment]
> 唉唉，才挂了一下下就被412风控了

红字那种？你运气好像有点差…换个网络吧，这是全局风控

**Comment by schoolbag123** [comment]
全局风控是啥意思？是这个网络都风控了？

**Comment by ZianTT** [comment]
> 全局风控是啥意思？是这个网络都风控了？（例如有WIFI叫A，是A下面所有登录账号的请求都会被风控还是就风控我自己的账号一段时间?)

不太清楚，但是这个账号这个wifi应该是被风控了，简单有效的办法是换ip（网络环境），其他比如换账号之类的方案没测过

**Comment by schoolbag123** [comment]
那会过一段时间解封吗（大概半小时到一小时）
再问一个小问题，就是如果我多个人抢票，其中我这个挂A，B两个人，然后B自己也在抢，如果B抢到了，会不会影响这个脚本抢A的？

**Comment by ZianTT** [comment]
> 那会过一段时间解封吗（大概半小时到一小时）

是的，一般二十分钟左右

**Comment by schoolbag123** [comment]
就是会根据这个购买人信息连坐是吧，逆天
实际上我想问的是如果B抢到了，会不会导致本来抢AB的无法下单还是说会自动变成就抢A的票

**Comment by ZianTT** [comment]
> 就是会根据这个购买人信息连坐是吧，逆天
> 实际上我想问的是如果B抢到了，会不会导致本来抢AB的无法下单还是说会自动变成就抢A的票
> 然后如果脚本和人一起抢就要降脚本速度是吧

不完全是，是对这个网络环境如果判断异常会阻断这个环境的请求。

然后不管哪个脚本，最好放在两个文件夹运行，除了风控外不互相干扰的

**Comment by schoolbag123** [comment]
实际上我的意思是，我在这个电脑上面用脚本抢，然后为了防止脚本运气不好被风控，B自己也在用自己的手机抢，这种情况如果B运气好在脚本之前抢到了自己的票，那么脚本原来是抢AB两个人的票，在这种情况下后面是会因为有一个购票人已经有票导致整个请求无效还是说会自动（或者被啊b自动）变为就抢A的票😭

**Comment by ZianTT** [comment]
> 实际上我的意思是，我在这个电脑上面用脚本抢，然后为了防止脚本运气不好被风控，B自己也在用自己的手机抢，这种情况如果B运气好在脚本之前抢到了自己的票，那么脚本原来是抢AB两个人的票，在这种情况下后面是会因为有一个购票人已经有票导致整个请求无效还是说会自动（或者被啊b自动）变为就抢A的票😭
> 

hm你的意思是：
手机：单号抢一单单人票B
电脑脚本：单号抢一单双人票AB
是这样吗？
如果是这样，不会自动转A，因为下单的时候会提示一证多票，没有做过重复下单的判断，建议抢到之后电脑改掉，或者我推荐双脚本购票，但是需要降速或者两个网络（电脑）挂。

**Comment by ZianTT** [comment]
> <img width="973" alt="image" src="https://github.com/ZianTT/BHYG/assets/48409459/512640e0-c64e-4eb5-937f-7b25492a7d44">
> 
> 我把程序显示的准备网址打开来自己看，没想到也是提示这个，这是直接把我账号风控了吗😅
> 但是现在不提示412了¯\_(ツ)_/¯

程序的准备网址只能当前cookie使用，浏览器和脚本cookie不一样，你可能用不上
