### ISSUE TITLE
[Bug]: 0.6.1版本的扫码登录异常

### ISSUE THREAD

**Issue by WenyiDong** [ZianTT/BHYG#76]
### 描述这个Bug

扫码登录会报错

### 复现步骤

登录的时候选2也就是扫码登录，界面显示出二维码但是底下报错 AttributeError: 'PyPNGImage' object has no attribute 'show'

### 预期操作

应能正常进行扫码登录

### 截图

![image](https://github.com/ZianTT/BHYG/assets/62381678/7bc02d81-20e0-46c0-a814-d5f32445a47b)

### 问题版本

main分支-Release

### 日志

```shell
AttributeError: 'PyPNGImage' object has no attribute 'show'
```

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
问题已知悉

另外，我暂时无法确认您是正版用户，请提供您的用户名以备查验，谢谢

**Comment by ZianTT** [comment]
em…虽然确认是正版但是您是从哪里得到的0.6.1激活码的呢？我和代理都想不起来了…

**Comment by ZianTT** [comment]
Fixed in v0.6.2
